### ISSUE TITLE
Forgot to Add Angular In the Frameworks section

### ISSUE THREAD

**Issue by abughurab16** [Abdullah-webdev/ResourcesMark#1]
first off thanks for the amazing website you run but since you put vue,react.. i think it would be fair to add Angular too as it it also quite popular

**Comment by Abdullah-Sajjad026** [comment]
Thanks for suggestion.

**Comment by abughurab16** [comment]
no problem.. also your website is really amazing .. thank you for everything!!

**Comment by Abdullah-Sajjad026** [comment]
Angular Added.
